### Create user
POST http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "phone_number": "+7999113344"
}

# Response:
# - 201: Created
# - 422: Unprocessable Entity
# - 429: Too Many Requests

### Authenticate user
POST http://localhost:3000/api/user_token HTTP/1.1
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "phone_number": "+7999113344",
  "password": "2615"
}

# Response:
# - 201: Created
# - 404: Not Found

### Update user
PATCH http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTQ5NTE4MjAsInN1YiI6MX0.AjmuiZ3F81b0GvrKZdqtWeRkAujueG_dGS4kJLcap6M
Accept: application/json
Content-Type: application/json

{
  "email": "mail@mail.ru",
  "first_name": "First"
}

# Response:
# - 200: OK
# - 401: Unauthorized
# - 422: Unprocessable Entity

### Show user
GET http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTQ5NTE4MjAsInN1YiI6MX0.AjmuiZ3F81b0GvrKZdqtWeRkAujueG_dGS4kJLcap6M
Accept: application/json

# Response:
# - 200: Ok
# - 401: Unauthorized

### Show receipts
GET http://localhost:3000/api/receipts?start_from=1&limit=2 HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwMzM0NjYsInN1YiI6Mn0.aEZxJWpvDhQtdgkoU40Vmtpk5YLkH-6UD9NRjD0kuf4
Accept: application/json

# Response:
# - 200: OK
# - 401: Unauthorized

### Create receipt
POST http://localhost:3000/api/receipts HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwMzM0NjYsInN1YiI6Mn0.aEZxJWpvDhQtdgkoU40Vmtpk5YLkH-6UD9NRjD0kuf4
Accept: application/json
Content-Type: application/json

{
  "qr_string": "t=20190113T154800&s=127.00&fn=8716000100025114&i=114318&fp=3578721879&n=1"
}

# Response:
# - 201: Created
# - 422: Unprocessable Entity

### Index home
GET http://localhost:3000/api/home HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwMzM0NjYsInN1YiI6Mn0.aEZxJWpvDhQtdgkoU40Vmtpk5YLkH-6UD9NRjD0kuf4
Accept: application/json

# Response:
# - 200: OK
# - 401: Unauthorized

### Assign vending machine
POST http://localhost:3000/api/vending_machines/75576448/assign HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDI2NzgyNjUsInN1YiI6MX0.Eb76MOGXxC8XcZh1QBwO1Nidou5kZzeu49BFWwxsSBM
Accept: application/json
Content-Type: application/json

{
  "receipt_id": 2
}


# Response:
# - 200: OK
# - 401: Unauthorized
# - 422: Unprocessable Entity

### Take item from vending machine
POST http://localhost:3000/api/vending_machines/75576448/take_item HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDI2NzgyNjUsInN1YiI6MX0.Eb76MOGXxC8XcZh1QBwO1Nidou5kZzeu49BFWwxsSBM
Accept: application/json
Content-Type: application/json

{
  "column": 1,
  "row": 2,
  "item_id": 1,
  "receipt_id": 2
}

# Response:
# - 200: OK
# - 401: Unauthorized
# - 422: Unprocessable Entity
