### Create user
POST http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "phone_number": "+7999112233"
}

# Response:
# - 201: Created
# - 422: Unprocessable Entity
# - 429: Too Many Requests

### Authenticate user
POST http://localhost:3000/api/user_token HTTP/1.1
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "phone_number": "+77999112233",
  "password": "8256"
}

# Response:
# - 201: Created
# - 404: Not Found

### Update user
PATCH http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTQ5NTE4MjAsInN1YiI6MX0.AjmuiZ3F81b0GvrKZdqtWeRkAujueG_dGS4kJLcap6M
Accept: application/json
Content-Type: application/json

{
  "email": "mail@mail.ru",
  "first_name": "First"
}

# Response:
# - 200: OK
# - 401: Unauthorized
# - 422: Unprocessable Entity

### Show user
GET http://localhost:3000/api/user HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTQ5NTE4MjAsInN1YiI6MX0.AjmuiZ3F81b0GvrKZdqtWeRkAujueG_dGS4kJLcap6M
Accept: application/json

# Response:
# - 200: Ok
# - 401: Unauthorized

### Show receipts
GET http://localhost:3000/api/receipts HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwMzM0NjYsInN1YiI6Mn0.aEZxJWpvDhQtdgkoU40Vmtpk5YLkH-6UD9NRjD0kuf4
Accept: application/json

# Response:
# - 200: OK
# - 401: Unauthorized

### Create receipt
POST http://localhost:3000/api/receipts HTTP/1.1
API-Version: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwMzM0NjYsInN1YiI6Mn0.aEZxJWpvDhQtdgkoU40Vmtpk5YLkH-6UD9NRjD0kuf4
Accept: application/json
Content-Type: application/json

{
  "qr_string": "t=20190113T154800&s=127.00&fn=8716000100025114&i=114318&fp=3578721879&n=1"
}

# Response:
# - 201: Created
# - 422: Unprocessable Entity
