### Create user
POST /api/user HTTP/1.1
Host: localhost:3000
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "phone_number": "+7999112233"
}

### Update user
PATCH /api/user HTTP/1.1
Host: localhost:3000
API-Version: 1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
Accept: application/json
Content-Type: application/json

{
  "email": "mail@mail.ru",
  "first_name": "First"
}

### Authenticate user
POST /api/user_token HTTP/1.1
Host: localhost:3000
API-Version: 1
Accept: application/json
Content-Type: application/json

{
  "auth": {
    "phone_number": "+7999112233",
    "password": "1234"
  }
}